### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by abhishekgupta92** [B-3PO/angular-material-event-calendar#5]
I used the library in a project and it was quite helpful. I added a very small hack to the same

https://github.com/B-3PO/angular-material-event-calendar/pull/4

Would be happy to help otherwise as well.

**Comment by B-3PO** [comment]
k, ill check it out and try to get a new release out this weekend

**Comment by abhishekgupta92** [comment]
@B-3PO Thanks :)

**Comment by B-3PO** [comment]
released in v0.1.3
