### ISSUE TITLE
Readme refers to wrong project

### ISSUE THREAD

**Issue by TesseractG** [B-3PO/angular-material-event-calendar#6]
In the readme, you state;

> To add Expansion Panels to you angular-material project, include the material.components.expansionPanels module as a dependency in your application.
>
> angular.module('myApp', ['ngMaterial', 'material.components.expansionPanels']);

This is obviously copied from your Expansion Panels project and not changed. At first I thought the calendar depends on expansion panels, but it turns out to be not the case.

Just a heads up, nothing major, but it might be a good idea to fix.

**Comment by TesseractG** [comment]
Fixed in pull request #8

**Comment by B-3PO** [comment]
Thanks, ill get this merged

**Comment by B-3PO** [comment]
Fixed, thanks
