### ISSUE TITLE
Days of next month shows different on calendar

### ISSUE THREAD

**Issue by nadien** [B-3PO/angular-material-event-calendar#9]
Hi everybody, i have a trouble with calendar, it shows weird the days on the calendar.

I leave capture:
![captura de pantalla_2017-01-07_14-00-52](https://cloud.githubusercontent.com/assets/3813688/21744784/52ba9266-d4e2-11e6-9417-eed4213720df.png)

Look at the days of next month and every month i stay it shows similar; days wrong.

What can i do to fix this?.

Regards :)

**Comment by B-3PO** [comment]
Hey, i will take a look at this, sorry for the delay

**Comment by alexgarciab** [comment]
Any updates on this @B-3PO? Having the same issue here.

**Comment by B-3PO** [comment]
Its on my todo list, will let you know when its done

**Comment by alexgarciab** [comment]
@B-3PO we are developing a platform right now with this calendar integrated. We need to make a decision whether to wait until it's fixed or change it. Any TAT for the bug fix?

**Comment by B-3PO** [comment]
i will try to get it done tonight in a branch so you can test, then we can release a new version

**Comment by B-3PO** [comment]
change merged into master. Can you please install master and verify that this fixes your problem.
Thanks

**Comment by nadien** [comment]
Hi, thanks for the answer, i'm pretty grateful with you , but there is a problem with it yet.
I made sure the files were replaced by latest commit and it is. But still with the days show incorrect.
Previous days of month work sucessfully.


![2017-02-07_04-53-43](https://cloud.githubusercontent.com/assets/3813688/22688480/18d8c78e-ecf2-11e6-83bd-596c78d85eb6.png)

**Comment by B-3PO** [comment]
If you install the branch i pushed (#9-next-month-days) and run the the test app(gulp), do you see the month correctly? This works correctly on my computer.

**Comment by B-3PO** [comment]
Also how are you installing this module(bower, npm)?

**Comment by nadien** [comment]
Thanks 
-Also how are you installing this module(bower, npm)?

I'm using npm with angular-fullstack on typescript.

So, i've cloned the repository in a new folder and works fine. Show everything good, but there is something in Typescript with Date's i've had issue with it when i merge files.

I don't know why but i need to put MomentJS to get the date fine with some scripts i do. Maybe there is something that make the issue with angular-material-event-calendar.

I'm not trying to convert this in a support thread but your help will be awesome. Please tell me if there is something you can do in the files, i will be grateful. If no, not problem i will check the code to fix this.

Thanks :+1:  and regards.

**Comment by B-3PO** [comment]
are you using any css minification?

**Comment by B-3PO** [comment]
If the repo on its own is working then i'm at a loss, i am not familiar with angular full stack. I would look at the changes i made in the branch and then look at the file loaded in your browser to see if those changes exist
